{% set name = "stanza" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stanza-{{ version }}.tar.gz
  sha256: 70d0c16aecebce878b37b50d2495c81c230dfca36f8f3f20831b957005fa10f3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - protobuf
    - python >=3.6
    - requests
    - pytorch >=1.3.0
    - tqdm

test:
  imports:
    - stanza
    - stanza.models
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stanfordnlp/stanza
  summary: A Python NLP Library for Many Human Languages, by the Stanford NLP Group
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - FernandezMathieu
